# Generated by Django 6.0.2 on 2026-02-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_contactmessage_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення з контактів'},
        ),
    ]
